services:
  vernemq:
    image: vernemq/vernemq:2.0.0-alpine
    container_name: vernemq
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - power_hub_control
    environment:
      DOCKER_VERNEMQ_ACCEPT_EULA: "yes"
      DOCKER_VERNEMQ_USER_power-hub: ${MQTT_PASSWORD}
      DOCKER_VERNEMQ_ALLOW_ANONYMOUS: "on"
      DOCKER_VERNEMQ_LISTENER__WS__DEFAULT: "0.0.0.0:9001"
      DOCKER_VERNEMQ_PLUGINS__VMQ_BRIDGE: "on" #https://docs.vernemq.com/configuring-vernemq/bridge
      DOCKER_VERNEMQ_VMQ_BRIDGE__TCP__BR0: "${CLOUD_VERNEMQ_URL}"
      DOCKER_VERNEMQ_VMQ_BRIDGE__TCP__BR0__TOPIC__1: "power_hub/* out 1"
      DOCKER_VERNEMQ_VMQ_BRIDGE__TCP__BR0__username: "power_hub"
      DOCKER_VERNEMQ_VMQ_BRIDGE__TCP__BR0__password: ${MQTT_PASSWORD}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/health"]
      interval: 5s
      timeout: 5s
      retries: 5

  control:
    depends_on:
      vernemq:
        condition: service_healthy
    container_name: control
    build:
      context: .
      dockerfile: python_script.Dockerfile
    command: "energy_box_control.power_hub_control"
    networks:
      - power_hub_control
    env_file:
      - .env
    environment:
      - PAGERDUTY_KEY=$PAGERDUTY_KEY
    restart: on-failure:5

networks:
  power_hub_control:
